Repository DUT-Info-Montreuil/SAE-5.A-carmate-front, pull requests merged in 2024-01, with the labels that each got.

#25 feat(create-subscription): user create subscription to regular carpooling
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/interface/carpooling.ts
  src/app/layout/create-subscription/create-subscription.component.html
  src/app/layout/create-subscription/create-subscription.component.scss
  src/app/layout/create-subscription/create-subscription.component.spec.ts
  src/app/layout/create-subscription/create-subscription.component.ts
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/nav-bar/nav-bar.component.ts
  src/app/service/carpooling/carpooling.service.mock.ts
  src/app/service/carpooling/carpooling.service.spec.ts
  src/app/service/carpooling/carpooling.service.ts
  src/styles.scss
Labels: enhancement

#30 refactor(publish-carpool-test): optimize unit test execution
  src/app/layout/publish-carpool/publish-carpool.component.spec.ts
Labels: refactor

#29 feat(history-subscription): list own subscriptions
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/interface/carpooling.ts
  src/app/interface/other.ts
  src/app/layout/carpooling/carpooling.component.spec.ts
  src/app/layout/carpooling/carpooling.component.ts
  src/app/layout/create-subscription/create-subscription.component.spec.ts
  src/app/layout/create-subscription/create-subscription.component.ts
  src/app/layout/home-page/home-page.component.spec.ts
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/nav-bar/nav-bar.component.ts
  src/app/layout/publish-carpool/publish-carpool.component.spec.ts
  src/app/layout/publish-carpool/publish-carpool.component.ts
  src/app/layout/result-carpool/result-carpool.component.spec.ts
  src/app/layout/result-carpool/result-carpool.component.ts
  src/app/layout/search-bar/search-bar.component.spec.ts
  src/app/layout/search-bar/search-bar.component.ts
  src/app/layout/trips-page/subscription/subscription-dialog/subscription-dialog.component.html
  src/app/layout/trips-page/subscription/subscription-dialog/subscription-dialog.component.scss
  src/app/layout/trips-page/subscription/subscription-dialog/subscription-dialog.component.spec.ts
  src/app/layout/trips-page/subscription/subscription-dialog/subscription-dialog.component.ts
  src/app/layout/trips-page/subscription/subscription.component.html
  src/app/layout/trips-page/subscription/subscription.component.scss
  src/app/layout/trips-page/subscription/subscription.component.spec.ts
  src/app/layout/trips-page/subscription/subscription.component.ts
  src/app/layout/trips-page/trips-page.component.html
  src/app/layout/trips-page/trips-page.component.scss
  src/app/layout/trips-page/trips-page.component.spec.ts
  src/app/layout/trips-page/trips-page.component.ts
  src/app/service/address/address.service.mock.ts
  src/app/service/address/address.service.ts
  src/app/service/carpooling/carpooling.service.mock.ts
  src/app/service/carpooling/carpooling.service.ts
Labels: enhancement

#26 feat(reserve-carpooling): reserve carpooling
  src/app/app.module.ts
  src/app/interface/carpooling.ts
  src/app/layout/carpooling-dialog/carpooling-dialog.component.html
  src/app/layout/carpooling-dialog/carpooling-dialog.component.scss
  src/app/layout/carpooling-dialog/carpooling-dialog.component.spec.ts
  src/app/layout/carpooling-dialog/carpooling-dialog.component.ts
  src/app/layout/carpooling/carpooling.component.html
  src/app/layout/carpooling/carpooling.component.spec.ts
  src/app/layout/carpooling/carpooling.component.ts
  src/app/layout/home-page/home-page.component.spec.ts
  src/app/layout/result-carpool/result-carpool.component.html
  src/app/layout/result-carpool/result-carpool.component.spec.ts
  src/app/layout/result-carpool/result-carpool.component.ts
  src/app/layout/trips-page/subscription/subscription.component.spec.ts
  src/app/layout/trips-page/trips-page.component.spec.ts
  src/app/service/carpooling/carpooling.service.mock.ts
  src/app/service/carpooling/carpooling.service.ts
  src/app/service/score/score.service.mock.ts
  src/app/service/score/score.service.spec.ts
Labels: enhancement

#34 feat(my-carpoolings): see my history
  src/app/app.module.ts
  src/app/interface/carpooling.ts
  src/app/layout/trips-page/my-carpoolings/carpooling-dialog/carpooling-dialog.component.html
  src/app/layout/trips-page/my-carpoolings/carpooling-dialog/carpooling-dialog.component.scss
  src/app/layout/trips-page/my-carpoolings/carpooling-dialog/carpooling-dialog.component.spec.ts
  src/app/layout/trips-page/my-carpoolings/carpooling-dialog/carpooling-dialog.component.ts
  src/app/layout/trips-page/my-carpoolings/my-carpoolings.component.html
  src/app/layout/trips-page/my-carpoolings/my-carpoolings.component.scss
  src/app/layout/trips-page/my-carpoolings/my-carpoolings.component.spec.ts
  src/app/layout/trips-page/my-carpoolings/my-carpoolings.component.ts
  src/app/layout/trips-page/trips-page.component.html
  src/app/layout/trips-page/trips-page.component.spec.ts
  src/app/layout/trips-page/trips-page.component.ts
  src/app/service/carpooling/carpooling.service.mock.ts
  src/app/service/carpooling/carpooling.service.ts
Labels: enhancement

#5 feat(admin): admin panel for validation document - UC-35
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/environement/environement.ts
  src/app/interface/admin.ts
  src/app/layout/admin/side-bar/side-bar.component.html
  src/app/layout/admin/side-bar/side-bar.component.scss
  src/app/layout/admin/side-bar/side-bar.component.spec.ts
  src/app/layout/admin/side-bar/side-bar.component.ts
  src/app/layout/admin/validation/document/validation_doc.component.html
  src/app/layout/admin/validation/document/validation_doc.component.scss
  src/app/layout/admin/validation/document/validation_doc.component.spec.ts
  src/app/layout/admin/validation/document/validation_doc.component.ts
  src/app/layout/admin/validation/list/validation_list.component.html
  src/app/layout/admin/validation/list/validation_list.component.scss
  src/app/layout/admin/validation/list/validation_list.component.spec.ts
  src/app/layout/admin/validation/list/validation_list.component.ts
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/root/root.component.ts
  src/app/service/admin/validation/MutualizedMockData.ts
  src/app/service/admin/validation/validation.service.mock.ts
  src/app/service/admin/validation/validation.service.ts
  src/app/service/admin/validation/validation_doc.service.spec.ts
  src/app/service/admin/validation/validation_list.service.spec.ts
Labels: enhancement

#45 update(docs): init docs for v1
  docs/DEVELOPMENT.md
  docs/HOWTO.md
Labels: documentation
